@echo off
rmdir /q /s build
mkdir build
pushd build
set CORRADE_BUILD=-DUTILITY_USE_ANSI_COLORS=OFF
set MAGNUM_BUILD=-DWITH_AUDIO=OFF -DWITH_SDL2APPLICATION=ON -DWITH_OBJIMPORTER=ON -DWITH_TGAIMPORTER=ON
:: set SDL2_BUILD=-DSDL_STATIC=OFF -DSDL_SHARED=ON -DFORCE_STATIC_VCRT=OFF -DLIBC=ON
set VCPKG=-DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake ..
cmake .. %CORRADE_BUILD% %MAGNUM_BUILD% %SDL2_BUILD% %VCPKG% -G "Visual Studio 14 2015"
:: cmake .. %CORRADE_BUILD% %MAGNUM_BUILD% %SDL2_BUILD% %VCPKG% -G "Sublime Text 2 - Ninja"
popd